# Generated by Django 3.1.5 on 2021-01-20 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210119_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_funded',
            field=models.BooleanField(default=False),
        ),
    ]
